### ISSUE TITLE
two memory leaks (softblock) in commit 

### ISSUE THREAD

**Issue by piru** [tonioni/pfs3aio#1]
commit cb4ee3c9133dcb67c9400b7bc3586649ec8f3659 introduced dynamic softblock as well as my fixes. the softblock changes introduced two memory leaks:

1. softblock is leaked at https://github.com/tonioni/pfs3aio/blob/cb4ee3c9133dcb67c9400b7bc3586649ec8f3659/directory.c#L2434

2. softblock is leaked at
https://github.com/tonioni/pfs3aio/blob/cb4ee3c9133dcb67c9400b7bc3586649ec8f3659/directory.c#L2532

**Comment by tonioni** [comment]
Fixed, I was not finished with these extra changes but I forgot and pushed them..
